// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oesophagus/oesophagus.proto

package oesophagus

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Swallow struct {
	Measurement          string   `protobuf:"bytes,1,opt,name=measurement,proto3" json:"measurement,omitempty"`
	FieldSet             string   `protobuf:"bytes,2,opt,name=fieldSet,proto3" json:"fieldSet,omitempty"`
	TagSet               string   `protobuf:"bytes,3,opt,name=tagSet,proto3" json:"tagSet,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Swallow) Reset()         { *m = Swallow{} }
func (m *Swallow) String() string { return proto.CompactTextString(m) }
func (*Swallow) ProtoMessage()    {}
func (*Swallow) Descriptor() ([]byte, []int) {
	return fileDescriptor_be20434a839d7ed5, []int{0}
}

func (m *Swallow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Swallow.Unmarshal(m, b)
}
func (m *Swallow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Swallow.Marshal(b, m, deterministic)
}
func (m *Swallow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Swallow.Merge(m, src)
}
func (m *Swallow) XXX_Size() int {
	return xxx_messageInfo_Swallow.Size(m)
}
func (m *Swallow) XXX_DiscardUnknown() {
	xxx_messageInfo_Swallow.DiscardUnknown(m)
}

var xxx_messageInfo_Swallow proto.InternalMessageInfo

func (m *Swallow) GetMeasurement() string {
	if m != nil {
		return m.Measurement
	}
	return ""
}

func (m *Swallow) GetFieldSet() string {
	if m != nil {
		return m.FieldSet
	}
	return ""
}

func (m *Swallow) GetTagSet() string {
	if m != nil {
		return m.TagSet
	}
	return ""
}

func (m *Swallow) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type Burp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Burp) Reset()         { *m = Burp{} }
func (m *Burp) String() string { return proto.CompactTextString(m) }
func (*Burp) ProtoMessage()    {}
func (*Burp) Descriptor() ([]byte, []int) {
	return fileDescriptor_be20434a839d7ed5, []int{1}
}

func (m *Burp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Burp.Unmarshal(m, b)
}
func (m *Burp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Burp.Marshal(b, m, deterministic)
}
func (m *Burp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Burp.Merge(m, src)
}
func (m *Burp) XXX_Size() int {
	return xxx_messageInfo_Burp.Size(m)
}
func (m *Burp) XXX_DiscardUnknown() {
	xxx_messageInfo_Burp.DiscardUnknown(m)
}

var xxx_messageInfo_Burp proto.InternalMessageInfo

func (m *Burp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Burp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Swallow)(nil), "Swallow")
	proto.RegisterType((*Burp)(nil), "Burp")
}

func init() { proto.RegisterFile("oesophagus/oesophagus.proto", fileDescriptor_be20434a839d7ed5) }

var fileDescriptor_be20434a839d7ed5 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xcd, 0x4e, 0x86, 0x30,
	0x10, 0x45, 0xc5, 0xef, 0x07, 0x18, 0x57, 0x76, 0x61, 0x1a, 0x64, 0x41, 0x58, 0xb1, 0xc2, 0xa8,
	0x1b, 0xd7, 0xfa, 0x00, 0x26, 0xf0, 0x04, 0x55, 0x47, 0x24, 0xa1, 0xb4, 0xe9, 0x4c, 0x65, 0xe5,
	0xbb, 0x1b, 0x9a, 0x0a, 0xee, 0xe6, 0xdc, 0x9b, 0xc9, 0xcd, 0x81, 0x5b, 0x83, 0x64, 0xec, 0x97,
	0x1a, 0x3c, 0xdd, 0xed, 0x67, 0x6b, 0x9d, 0x61, 0x53, 0xff, 0x40, 0xda, 0x2f, 0x6a, 0x9a, 0xcc,
	0x22, 0x2a, 0xb8, 0xd2, 0xa8, 0xc8, 0x3b, 0xd4, 0x38, 0xb3, 0x4c, 0xaa, 0xa4, 0xc9, 0xbb, 0xff,
	0x91, 0x28, 0x20, 0xfb, 0x1c, 0x71, 0xfa, 0xe8, 0x91, 0xe5, 0x65, 0xa8, 0x37, 0x16, 0x37, 0x70,
	0x66, 0x35, 0xac, 0xcd, 0x21, 0x34, 0x91, 0x44, 0x09, 0x39, 0x8f, 0x1a, 0x89, 0x95, 0xb6, 0xf2,
	0x58, 0x25, 0xcd, 0xa1, 0xdb, 0x83, 0xfa, 0x09, 0x8e, 0xcf, 0xde, 0xd9, 0xf5, 0x9b, 0x58, 0xb1,
	0xa7, 0x30, 0x7b, 0xea, 0x22, 0x09, 0x09, 0xa9, 0x46, 0x22, 0x35, 0x60, 0x1c, 0xfc, 0xc3, 0x87,
	0x7b, 0xb8, 0x7e, 0xdd, 0x64, 0x7a, 0x74, 0xdf, 0xe3, 0x3b, 0x8a, 0x12, 0xd2, 0x17, 0x33, 0x93,
	0xd7, 0x28, 0xb2, 0x36, 0x7a, 0x15, 0xa7, 0x76, 0x9d, 0xa8, 0x2f, 0xde, 0xce, 0x41, 0xf9, 0xf1,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xa8, 0x0e, 0x5f, 0x11, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OesophagusServiceClient is the client API for OesophagusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OesophagusServiceClient interface {
	Consume(ctx context.Context, in *Swallow, opts ...grpc.CallOption) (*Burp, error)
}

type oesophagusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOesophagusServiceClient(cc grpc.ClientConnInterface) OesophagusServiceClient {
	return &oesophagusServiceClient{cc}
}

func (c *oesophagusServiceClient) Consume(ctx context.Context, in *Swallow, opts ...grpc.CallOption) (*Burp, error) {
	out := new(Burp)
	err := c.cc.Invoke(ctx, "/OesophagusService/Consume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OesophagusServiceServer is the server API for OesophagusService service.
type OesophagusServiceServer interface {
	Consume(context.Context, *Swallow) (*Burp, error)
}

// UnimplementedOesophagusServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOesophagusServiceServer struct {
}

func (*UnimplementedOesophagusServiceServer) Consume(ctx context.Context, req *Swallow) (*Burp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}

func RegisterOesophagusServiceServer(s *grpc.Server, srv OesophagusServiceServer) {
	s.RegisterService(&_OesophagusService_serviceDesc, srv)
}

func _OesophagusService_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Swallow)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OesophagusServiceServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/OesophagusService/Consume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OesophagusServiceServer).Consume(ctx, req.(*Swallow))
	}
	return interceptor(ctx, in, info, handler)
}

var _OesophagusService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "OesophagusService",
	HandlerType: (*OesophagusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Consume",
			Handler:    _OesophagusService_Consume_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oesophagus/oesophagus.proto",
}
